apiVersion: batch/v1
kind: Job
metadata:
  generateName: sync-hook
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: sync-hook
    spec:
      containers:
      - name: alpine
        image: alpine
        command:
          - "sh"
          - "-c"
        args:
        - "sleep 10"
        imagePullPolicy: IfNotPresent
