apiVersion: batch/v1
kind: Job
metadata:
  generateName: post-sync-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  activeDeadlineSeconds: 600
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: post-sync
    spec:
      restartPolicy: "OnFailure"
      containers:
      - name: alpine
        image: alpine
        args: ["sleep", "10"]
        command: ["sh", "-c"]
