apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sync-wave1
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "200m"
            memory: "250Mi"
        ports:
          - name: traffic
            containerPort: 80
            protocol: TCP
      #   volumeMounts:
      #   - name: hostpath
      #     mountPath: /new
      # volumes:
      # - name: hostpath
      #   emptyDir: {}
